spring.application.name=ExceptionHandling
spring.datasource.url=jdbc:mysql://localhost:3306/exceptiondb
spring.datasource.username=root
spring.datasource.password=root@123
server.port=2205
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always